# Generated by Django 4.2.7 on 2023-11-30 19:50

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_marketuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='firstname',
            field=models.CharField(max_length=50, null=True, validators=[base.models.validate_alpha]),
        ),
        migrations.AddField(
            model_name='marketuser',
            name='lastname',
            field=models.CharField(max_length=50, null=True, validators=[base.models.validate_alpha]),
        ),
    ]
