# Generated by Django 4.2.7 on 2023-12-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_marketuser_firstname_marketuser_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customername',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
