# Generated by Django 4.2.6 on 2023-12-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_receipt_customername_alter_receipt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=80, null=True)),
                ('percent', models.FloatField(null=True)),
                ('min_price', models.FloatField(default=100, null=True)),
            ],
        ),
    ]
