# Generated by Django 4.2.6 on 2024-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
