# Generated by Django 4.2.6 on 2024-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_receipt_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='orderid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
